version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_USER: user
      DB_NAME: dbname
      DB_SSLMODE: disable
      DB_PASSWORD: password
    depends_on:
      - db

  db:
    image: postgres:16.2-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: dbname
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
